language: python
group: travist_latest

env:
  global:
    - CYTHON_TRACE_NOGIL=1


matrix:
  include:
    # only test latest python for OSX
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8

    # Test for full range
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.8


before_install:
  - uname -a
  # get the right anaconda version
  - |
     if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
     else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
     fi
  - mkdir $HOME/.conda
  - bash miniconda.sh -b -p $HOME/miniconda
  - $HOME/miniconda/bin/conda init bash
  - source ~/.bash_profile
  - conda activate base
  - conda update --yes conda
  - uname -a


install:
  - conda env create python=$PYTHON_VERSION -f devtools/environment.yml --quiet
  - source activate propkatraj
  - python -V
    # Build and install package
  - pip install -e .


script:
  - pytest -v --disable-pytest-warnings --cov=propkatraj propkatraj/tests/

notifications:
    email: false

after_success:
  - codecov
