name: propkatraj
channels:
  - conda-forge
dependencies:
  - setuptools>=61.2,<81
  - MDAnalysis>=2.0.0
  - MDAnalysisTests>=2.0.0
  - pandas
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - propka==3.1.0

