name: propkatraj
channels:
  - conda-forge
  - defaults
dependencies:
  - MDAnalysis>=2.0.0
  - MDAnalysisTests>=2.0.0
  - pandas
  - pytest
  - pytest-cov
  - codecov
  - pip
  - pip:
    - propka==3.1
