name: docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs:
    if: "github.repository == 'Becksteinlab/propkatraj'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0         

    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        environment-file: docs/requirements.yaml
        add-pip-as-python-dependency: true
        architecture: x64

        miniforge-variant: Mambaforge
        use-mamba: true
        channels: conda-forge

        activate-environment: propkatrajdocs
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true 

    - name: install dependencies
      run: |
        pip install pandas MDAnalysis propka==3.1

    - name: install propkatraj
      run: |
        pip install .

    - name: build docs
      run: |
        cd docs && sphinx-build -T -E --keep-going -b html -D language=en sphinx html

    - name: deploy docs
      if: github.event_name != 'pull_request'    
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        user_name: 'github-actions'
        user_email: 'github-action@users.noreply.github.com'
